image:
  name: avptp/face
  tag: nil

registry:
  name: nil
  credentials: nil

deployment:
  replicas:
    min: 2
    max: 10
  revisionHistoryLimit: 2
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 20m
      memory: 30Mi

ingress:
  hosts: []
  middlewares:
    - redirectWww@file
    - setFrontHeaders@file

tls:
  dnsNames: []
