services:
  app:
    build:
      context: .
      target: development
      args:
        - USER_ID=${UID:-1000}
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app
    ports:
      - ${WEB_PORT:-80}:3000
