services:
  node:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - ${HTTP_PORT:-80}:3000
    tty: true
