kind: Deployment
apiVersion: apps/v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/change-cause: '{{ .Values.image.tag }}'

spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname

      containers:
        - name: default
          image: {{ template "image" . }}
          ports:
            - name: h1
              containerPort: 3000
            - name: h2
              containerPort: 3001
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: h1
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: h1
            initialDelaySeconds: 10

      imagePullSecrets:
        - name: registry
