kind: NetworkPolicy
apiVersion: networking.k8s.io/v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              namespace: networking
      ports:
        - port: http
    - from:
        - namespaceSelector:
            matchLabels:
              namespace: default
        - podSelector:
            matchLabels:
              app: mask
      ports:
        - port: http
