kind: PodDisruptionBudget
apiVersion: policy/v1beta1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}

  minAvailable: {{ .Values.deployment.replicas.min }}
