kind: Secret
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-registry
  namespace: {{ .Release.Namespace }}

type: kubernetes.io/dockerconfigjson

stringData:
  .dockerconfigjson: {{ .Values.registry.credentials }}
