kind: Secret
apiVersion: v1

metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}

type: kubernetes.io/dockerconfigjson

stringData:
  .dockerconfigjson: |-
    {{ .Values.registry.credentials | nindent 4 }}
