kind: Service
apiVersion: v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: h1
      port: 80
      targetPort: h1
    - name: h2
      port: 81
      targetPort: h2
